version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: job_board_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: jobportal
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

# Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: biocompute_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@postgres:5432/jobportal?schema=public
      - JWT_SECRET=${JWT_SECRET:-6E4257C1266AEA121EB47DEB16961DA6}
      - NODE_ENV=production
    depends_on:
      - postgres
    networks:
      - biocompute_network
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npx prisma db seed &&
        npm start
      "

networks:
  biocompute_network:
    driver: bridge


volumes:
  postgres_data: